public class C10_typeAheadWrapper {

	/*public JSON2Apex[] jsApex;
	
	class JSON2Apex {
		public String id;	//EF  18LJ 241
		public String compressedId;	//EF18LJ241
		public String description;	//VALVE WATER REG
		public String stockingType;	//P
    }*/
    public String id;	//EF  18LJ 241
		public String compressedId;	//EF18LJ241
		public String description;	//VALVE WATER REG
		public String stockingType;	//P
	
}