global class CaseWrapper{
        @AuraEnabled
        public String caseId;
        @AuraEnabled
        public String Subject;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public String caseNumber;
        @AuraEnabled
        public String purpose;
        @AuraEnabled
        public String subPurpose;
        @AuraEnabled
        public String contName;
        @AuraEnabled
        public String accName;
        @AuraEnabled
        public String phoneNumber;
        @AuraEnabled
        public String customerType;
        @AuraEnabled
        public String priority;
        @AuraEnabled
        public String source;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String brand;
        @AuraEnabled
        public String zsm;
        @AuraEnabled
        public String part;
        @AuraEnabled
        public String partNumber;
    
        @AuraEnabled
        public Decimal quantity;
        @AuraEnabled
        public String partDescription;
        @AuraEnabled
        public String planner;
        @AuraEnabled
        public String buyer;
        @AuraEnabled
        public String vendorCode;
        @AuraEnabled
        public String vendorName;
        @AuraEnabled
        public String stockingType;
        @AuraEnabled
        public String C10Order;
        @AuraEnabled
        public String customerPO;
        @AuraEnabled
        public String RCD_PO;
        @AuraEnabled
        public String quote;
    
        @AuraEnabled
        public String RMA;
        @AuraEnabled
        public Boolean RMASent;
        @AuraEnabled
        public String invoice;
        @AuraEnabled
        public String model;
        @AuraEnabled
        public String serial;
        @AuraEnabled
        public String expediteStatus;
        @AuraEnabled
        public DateTime commitTime;
        @AuraEnabled
        public Date vendorShipDate;
        @AuraEnabled
        public String vendorTracking;
        @AuraEnabled
        public Decimal daysOpen;
        @AuraEnabled
        public String solution;
        @AuraEnabled
        public String timeToClosure;
        @AuraEnabled
        public String comments;
        @AuraEnabled
        public String pubchkbox;
        @AuraEnabled
        public DateTime createdDate;
        @AuraEnabled
        public String distributor_customer;

        
    }