@isTest
public class Test_JWTDecryptFinal {

    public static testmethod void startJWTFinal(){
        JWTDecryptFinal jwtFinalCls = new JWTDecryptFinal();
        jwtFinalCls.getEmailDecrypt('fjLASvN2cUbgfMxiUEjXSRA55eIeLz0zOBQTJYl07Rq1iFsCpSgil7+ipKmPMF9bjobdrvyJZx9zqerTv1lpyO/kGexOrifqZHvT+Nac/rbZlT5bFsgLOwccgTxADzgngZb1semAN0GSDbmr9CpElipAY2VQ7A7FLxu+3dv/8/s=');
        jwtFinalCls.getFirstNameDecrypt('fjLASvN2cUbgfMxiUEjXSRA55eIeLz0zOBQTJYl07Rq1iFsCpSgil7+ipKmPMF9bjobdrvyJZx9zqerTv1lpyO/kGexOrifqZHvT+Nac/rbZlT5bFsgLOwccgTxADzgngZb1semAN0GSDbmr9CpElipAY2VQ7A7FLxu+3dv/8/s=');
        jwtFinalCls.getLastNameDecrypt('fjLASvN2cUbgfMxiUEjXSRA55eIeLz0zOBQTJYl07Rq1iFsCpSgil7+ipKmPMF9bjobdrvyJZx9zqerTv1lpyO/kGexOrifqZHvT+Nac/rbZlT5bFsgLOwccgTxADzgngZb1semAN0GSDbmr9CpElipAY2VQ7A7FLxu+3dv/8/s=');
        jwtFinalCls.getHVACIDDecrypt('fjLASvN2cUbgfMxiUEjXSRA55eIeLz0zOBQTJYl07Rq1iFsCpSgil7+ipKmPMF9bjobdrvyJZx9zqerTv1lpyO/kGexOrifqZHvT+Nac/rbZlT5bFsgLOwccgTxADzgngZb1semAN0GSDbmr9CpElipAY2VQ7A7FLxu+3dv/8/s=');
        jwtFinalCls.getSHIPTODecrypt('fjLASvN2cUbgfMxiUEjXSRA55eIeLz0zOBQTJYl07Rq1iFsCpSgil7+ipKmPMF9bjobdrvyJZx9zqerTv1lpyO/kGexOrifqZHvT+Nac/rbZlT5bFsgLOwccgTxADzgngZb1semAN0GSDbmr9CpElipAY2VQ7A7FLxu+3dv/8/s=');
        jwtFinalCls.getPhoneNo('fjLASvN2cUbgfMxiUEjXSR8VYr1MTDz1xZKUJt1t9SzVBxmDJpgRrb7/X6PEAXga/LO1H55tqVUubchMi01WE3HkGGS6GLd9QNXhPZd02kXHzLDdgItFa2CSUmhJ0lzKXGhq63MYSbOsFiFas3W3q/A4UDlccPb8IuWqmWWu90wO626gKBy524+yt1bsdyOhDodGG0mBfHoXmEj/fuhEVA==');
        jwtFinalCls.getUsername('RYXM/IwxiIKC5sVULzsf8OibTlwnKr0/W8fAoYUKbjN6wlgJLwqZQm4ac12RXJhukpzKirm5B0J5Qdw3B3DZap/suLEkQ7Tbzw3WcdJ6imp15hQjfc8BnWvd8jhL4sATvzOBqcDczb+IuhZ1ghrRHI+xsmuRPeA/sX9m1QhOEqjks5XM7We5j6ehDPyC0azGbQBjJk8qyB/zbMm/bZlnDw==');
    }
}